"""Stage complete revisions before publishing; serialize against user edits."""
from uuid import UUID, uuid4
from psycopg2.extras import Json, RealDictCursor
from app.core.db import get_connection, transaction


class DraftConflict(Exception):
    pass


def _snapshot(cur, proposal_id):
    cur.execute("""
        SELECT jsonb_build_object(
            'rfp', p.rfp_id,
            'sections', COALESCE((SELECT jsonb_agg(jsonb_build_array(s.section_id, s.updated_at)
                ORDER BY s.section_id) FROM proposal_sections s WHERE s.proposal_id=p.proposal_id), '[]'::jsonb),
            'requirements', COALESCE((SELECT jsonb_agg(jsonb_build_array(r.requirement_id, r.raw_text_content)
                ORDER BY r.requirement_id) FROM extracted_requirements r WHERE r.rfp_id=p.rfp_id), '[]'::jsonb)
        ) AS snapshot FROM proposals p WHERE p.proposal_id=%s
    """, (str(proposal_id),))
    row = cur.fetchone()
    if row is None:
        raise DraftConflict('Proposal no longer exists.')
    return row['snapshot']


def create(proposal_id, run_id=None):
    run_id = str(run_id or uuid4())
    with transaction() as conn, conn.cursor(cursor_factory=RealDictCursor) as cur:
        cur.execute('SELECT proposal_id FROM proposals WHERE proposal_id=%s FOR UPDATE', (str(proposal_id),))
        if cur.fetchone() is None:
            raise DraftConflict('Proposal no longer exists.')
        cur.execute("SELECT 1 FROM drafting_runs WHERE proposal_id=%s AND status IN ('queued','running')", (str(proposal_id),))
        if cur.fetchone():
            raise DraftConflict('A draft is already queued or running for this proposal.')
        snapshot = _snapshot(cur, proposal_id)
        cur.execute('INSERT INTO drafting_runs(run_id,proposal_id,snapshot) VALUES (%s,%s,%s)', (run_id, str(proposal_id), Json(snapshot)))
        cur.execute("UPDATE proposals SET drafting_status='drafting', drafting_failure_reason=NULL WHERE proposal_id=%s", (str(proposal_id),))
    return run_id


def start(run_id, proposal_id):
    with transaction() as conn, conn.cursor(cursor_factory=RealDictCursor) as cur:
        cur.execute("UPDATE drafting_runs SET status='running', updated_at=now() WHERE run_id=%s AND proposal_id=%s AND status IN ('queued','running') RETURNING run_id", (str(run_id), str(proposal_id)))
        return cur.fetchone() is not None


def outline_for(run_id, outline=None):
    with transaction() as conn, conn.cursor(cursor_factory=RealDictCursor) as cur:
        if outline is not None:
            cur.execute('UPDATE drafting_runs SET outline=COALESCE(outline,%s) WHERE run_id=%s', (Json(outline), str(run_id)))
        cur.execute('SELECT outline FROM drafting_runs WHERE run_id=%s', (str(run_id),))
        return cur.fetchone()['outline']


def staged(run_id, index):
    conn = get_connection()
    try:
        with conn.cursor() as cur:
            cur.execute('SELECT section_id FROM drafting_run_sections WHERE run_id=%s AND outline_index=%s', (str(run_id), index))
            row = cur.fetchone()
            return str(row[0]) if row else None
    finally:
        conn.close()


def stage(run_id, index, payload):
    section_id = str(uuid4())
    with transaction() as conn, conn.cursor() as cur:
        cur.execute("""INSERT INTO drafting_run_sections(run_id,outline_index,section_id,payload)
            VALUES (%s,%s,%s,%s) ON CONFLICT (run_id,outline_index) DO UPDATE SET payload=EXCLUDED.payload
            RETURNING section_id""", (str(run_id), index, section_id, Json(payload)))
        return cur.fetchone()[0]


def publish(run_id):
    from app.services import document_service as docs
    with transaction() as conn, conn.cursor(cursor_factory=RealDictCursor) as cur:
        cur.execute('SELECT proposal_id FROM drafting_runs WHERE run_id=%s', (str(run_id),))
        proposal_id = cur.fetchone()['proposal_id']
        cur.execute('SELECT proposal_id FROM proposals WHERE proposal_id=%s FOR UPDATE', (str(proposal_id),))
        cur.execute('SELECT * FROM drafting_runs WHERE run_id=%s FOR UPDATE', (str(run_id),))
        run = cur.fetchone()
        if run['status'] == 'completed':
            return
        if run['status'] not in ('queued', 'running'):
            raise DraftConflict('Draft run is no longer active.')
        if _snapshot(cur, proposal_id) != run['snapshot']:
            raise DraftConflict('Proposal or requirements changed during drafting. Your edits were preserved; start a new draft.')
        cur.execute('SELECT * FROM drafting_run_sections WHERE run_id=%s ORDER BY outline_index', (str(run_id),))
        sections = cur.fetchall()
        if not run['outline'] or len(sections) != len(run['outline']):
            raise DraftConflict('The draft is incomplete. Previous sections were preserved.')
        # Legacy sections are protected by default. Only output known to have
        # been generated by this revision mechanism and never edited is retired.
        cur.execute("DELETE FROM proposal_sections WHERE proposal_id=%s AND generated_run_id IS NOT NULL AND NOT user_modified AND status <> 'approved'", (str(proposal_id),))
        cur.execute('SELECT requirement_id,section_title FROM proposal_sections WHERE proposal_id=%s', (str(proposal_id),))
        protected = cur.fetchall()
        for section in sections:
            payload = section['payload']
            # Preserve the user's version of the same requirement/section.
            if any((payload.get('requirement_id') and str(p['requirement_id']) == payload['requirement_id']) or p['section_title'].strip().casefold() == payload['section_title'].strip().casefold() for p in protected):
                continue
            docs.insert_proposal_section(proposal_id=proposal_id, **payload, section_id=section['section_id'], generated_run_id=run_id)
            cur.execute('UPDATE drafting_trajectories SET section_id=%s WHERE run_id=%s AND outline_index=%s', (str(section['section_id']), str(run_id), section['outline_index']))
        cur.execute("UPDATE drafting_runs SET status='completed', updated_at=now(),error=NULL WHERE run_id=%s", (str(run_id),))
        cur.execute("UPDATE proposals SET drafting_status='drafted',drafting_failure_reason=NULL,updated_at=now() WHERE proposal_id=%s", (str(proposal_id),))


def fail(run_id, error):
    with transaction() as conn, conn.cursor() as cur:
        cur.execute("UPDATE drafting_runs SET status='failed',error=%s,updated_at=now() WHERE run_id=%s AND status IN ('queued','running') RETURNING proposal_id", (error[:500], str(run_id)))
        row = cur.fetchone()
        if row:
            cur.execute("UPDATE proposals SET drafting_status='draft_failed',drafting_failure_reason=%s WHERE proposal_id=%s", (error[:500], str(row[0])))
